### ISSUE TITLE
Use SVG instead of divs

### ISSUE THREAD

**Issue by raphaelgmelo** [idwall/idcrop#5]
This will allow us to make a polygonal selection for IDs \o/

I see the first incremental step as using SVG for the current boxed crop. After that, we can think of a polygonal crop

Some experimentations: https://jsfiddle.net/9cg9ngx5/

**Comment by brizental** [comment]
I'll work on this, but I'll try this with SVG and canvas and see what works best.

Experiments with canvas: http://jsfiddle.net/5afa1so3/

**Comment by brizental** [comment]
I had a really good result using canvas. I basically got it to work with much less code and much faster. Next week I'll put it in our own code. 

You guys can see it working already: https://codepen.io/brizental/pen/xPmovB
